name: Deploy Server

concurrency: production

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Deploy to server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SERVER_DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}
        run: |
          # Copy the server directory to the remote server
          rsync -avz --delete ./server/ ${SSH_USER}@${SSH_HOST}:/tmp/momentloop-server/

          # Execute the deployment using the server's justfile
          ssh ${SSH_USER}@${SSH_HOST} "cd /tmp/momentloop-server && \
            # Ensure just is installed on the remote server
            if ! command -v just &> /dev/null; then \
              echo 'Installing just on remote server...' && \
              if command -v brew &> /dev/null; then \
                brew install just; \
              else \
                echo 'Homebrew not found. Please install Homebrew on your macOS server.' && \
                exit 1; \
              fi \
            fi && \
            # Run the deploy recipe from the server's justfile
            just deploy ${SERVER_DEPLOY_PATH}"

          echo "Deployment completed successfully!"

          exit 0
